import { BoltFilled, FilledSquare, Json, Lovable, NodePin, NodePlay, NodePower, NodeSuccess, NodeTrash, NodeValidationError, PopOut, Retry, StatusCanceled, StatusCompleted, StatusError, StatusNew, StatusUnknown, StatusWaiting, StatusWarning, Text, Toolbox, Triangle, VectorSquare } from './custom-generated';
import {
  AlignRight,
  AlignLeft,
  AlignCenter,
  AlignJustify,
  ArrowLeft,
  ArrowRight,
  ArrowUp,
  ArrowDown,
  ArrowUpDown,
  ArrowLeftRight,
  ArrowBigLeft,
  ArrowBigRight,
  ArrowBigUp,
  ArrowBigDown,
  ArrowLeftCircle,
  ArrowRightCircle,
  ArrowUpCircle,
  ArrowDownCircle,
  Activity,
  Airplay,
  AlarmClock,
  AlarmClockCheck,
  AlarmClockMinus,
  AlarmClockOff,
  AlertCircle,
  AlertTriangle,
  AlertOctagon,
  Album,
  Ambulance,
  Anchor,
  Aperture,
  Apple,
  Archive,
  ArchiveRestore,
  ArchiveX,
  AreaChart,
  Armchair,
  ArrowRightLeft,
  ArrowUpFromLine,
  ArrowDownToLine,
  AtSign,
  Atom,
  AudioLines,
  AudioWaveform,
  Award,
  Axe,
  Axis3d,
  Baby,
  Backpack,
  Badge,
  BadgeCheck,
  BadgeDollarSign,
  BadgeHelp,
  BadgeInfo,
  BadgeMinus,
  BadgePercent,
  BadgePlus,
  BadgeX,
  BaggageClaim,
  Ban,
  Banana,
  Banknote,
  BarChart,
  BarChart2,
  BarChart3,
  BarChart4,
  BarChartHorizontal,
  Barcode,
  Baseline,
  Bath,
  Battery,
  BatteryCharging,
  BatteryFull,
  BatteryLow,
  BatteryMedium,
  Beaker,
  Bean,
  Bed,
  BedDouble,
  Beer,
  Bell,
  BellDot,
  BellMinus,
  BellOff,
  BellPlus,
  BellRing,
  Bike,
  Binary,
  Binoculars,
  Biohazard,
  Bird,
  Bitcoin,
  Blend,
  Blinds,
  Blocks,
  Bluetooth,
  BluetoothConnected,
  BluetoothOff,
  Bold,
  Bolt,
  Bomb,
  Bone,
  Book,
  BookA,
  BookAudio,
  BookCheck,
  BookCopy,
  BookDashed,
  BookDown,
  BookHeadphones,
  BookHeart,
  BookImage,
  BookKey,
  BookLock,
  BookMarked,
  BookMinus,
  BookOpen,
  BookOpenCheck,
  BookOpenText,
  BookPlus,
  BookText,
  BookType,
  BookUp,
  BookUp2,
  BookUser,
  BookX,
  Bookmark,
  BookmarkCheck,
  BookmarkMinus,
  BookmarkPlus,
  BookmarkX,
  BoomBox,
  Bot,
  Box,
  BoxSelect,
  Boxes,
  Braces,
  Brackets,
  Brain,
  BrainCircuit,
  BrainCog,
  Briefcase,
  BriefcaseMedical,
  BringToFront,
  Brush,
  Bug,
  BugOff,
  BugPlay,
  Building,
  Building2,
  Bus,
  BusFront,
  Cable,
  CableCar,
  Cake,
  CakeSlice,
  Calculator,
  Calendar,
  CalendarArrowDown,
  CalendarArrowUp,
  CalendarCheck,
  CalendarCheck2,
  CalendarClock,
  CalendarDays,
  CalendarFold,
  CalendarHeart,
  CalendarMinus,
  CalendarOff,
  CalendarPlus,
  CalendarRange,
  CalendarSearch,
  CalendarX,
  Camera,
  CameraOff,
  CandlestickChart,
  Candy,
  CandyCane,
  Cannabis,
  Captions,
  Car,
  CarFront,
  CarTaxiFront,
  Caravan,
  Carrot,
  CaseLower,
  CaseSensitive,
  CaseUpper,
  CassetteTape,
  Cast,
  Castle,
  Cat,
  Cctv,
  ChartArea,
  ChartBar,
  ChartBarBig,
  ChartBarStacked,
  ChartCandlestick,
  ChartColumn,
  ChartColumnBig,
  ChartColumnStacked,
  ChartGantt,
  ChartLine,
  ChartNetwork,
  ChartNoAxesColumn,
  ChartNoAxesCombined,
  ChartNoAxesGantt,
  ChartPie,
  ChartScatter,
  ChartSpline,
  Check,
  CheckCheck,
  CheckCircle,
  CheckSquare,
  ChevronDown,
  ChevronFirst,
  ChevronLast,
  ChevronLeft,
  ChevronRight,
  ChevronUp,
  ChevronsDown,
  ChevronsLeft,
  ChevronsRight,
  ChevronsUp,
  Chrome,
  Circle,
  CircleCheck,
  CircleCheckBig,
  CircleDashed,
  CircleDot,
  CircleDotDashed,
  CircleEllipsis,
  CircleEqual,
  CircleOff,
  CircleSlash,
  CircleX,
  CircuitBoard,
  Citrus,
  Clapperboard,
  Clipboard,
  ClipboardCheck,
  ClipboardCopy,
  ClipboardList,
  ClipboardMinus,
  ClipboardPaste,
  ClipboardPen,
  ClipboardPenLine,
  ClipboardPlus,
  ClipboardType,
  ClipboardX,
  Clock,
  Clock1,
  Clock10,
  Clock11,
  Clock12,
  Clock2,
  Clock3,
  Clock4,
  Clock5,
  Clock6,
  Clock7,
  Clock8,
  Clock9,
  ClockAlert,
  ClockArrowDown,
  ClockArrowUp,
  Cloud,
  CloudCog,
  CloudDrizzle,
  CloudFog,
  CloudHail,
  CloudLightning,
  CloudMoon,
  CloudOff,
  CloudRain,
  CloudSnow,
  CloudSun,
  Cloudy,
  Clover,
  Club,
  Code,
  Code2,
  CodeSquare,
  Codepen,
  Codesandbox,
  Coffee,
  Cog,
  Coins,
  Columns,
  Command,
  Compass,
  Component,
  Computer,
  Cone,
  Contact,
  Contact2,
  Container,
  Contrast,
  Cookie,
  CookingPot,
  Copy,
  CopyCheck,
  CopyMinus,
  CopyPlus,
  CopySlash,
  CopyX,
  Copyleft,
  Copyright,
  CornerDownLeft,
  CornerDownRight,
  CornerLeftDown,
  CornerLeftUp,
  CornerRightDown,
  CornerRightUp,
  CornerUpLeft,
  CornerUpRight,
  Cpu,
  CreditCard,
  Croissant,
  Crop,
  Cross,
  Crosshair,
  Crown,
  Cuboid,
  CupSoda,
  Currency,
  Cylinder,
  Dam,
  Database,
  DatabaseBackup,
  DatabaseZap,
  Delete,
  Dessert,
  Diameter,
  Diamond,
  DiamondMinus,
  DiamondPlus,
  Dice1,
  Dice2,
  Dice3,
  Dice4,
  Dice5,
  Dice6,
  Dices,
  Diff,
  Disc,
  Disc2,
  Disc3,
  DiscAlbum,
  Divide,
  DivideCircle,
  DivideSquare,
  Dna,
  DnaOff,
  Dog,
  DollarSign,
  Donut,
  DoorClosed,
  DoorOpen,
  Dot,
  Download,
  DraftingCompass,
  Drama,
  Dribbble,
  Drill,
  Droplet,
  Droplets,
  Drum,
  Drumstick,
  Dumbbell,
  Ear,
  EarOff,
  Earth,
  EarthLock,
  Eclipse,
  Edit,
  Edit2,
  Edit3,
  Egg,
  EggFried,
  Ellipsis,
  EllipsisVertical,
  Equal,
  EqualNot,
  Eraser,
  Euro,
  Expand,
  ExternalLink,
  Eye,
  EyeOff,
  Facebook,
  Factory,
  Fan,
  FastForward,
  Feather,
  Fence,
  FerrisWheel,
  Figma,
  File,
  FileArchive,
  FileAudio,
  FileAudio2,
  FileAxis3d,
  FileBadge,
  FileBarChart,
  FileBarChart2,
  FileBox,
  FileCheck,
  FileCheck2,
  FileClock,
  FileCode,
  FileCode2,
  FileCog,
  FileDiff,
  FileDigit,
  FileDown,
  FileHeart,
  FileImage,
  FileInput,
  FileJson,
  FileJson2,
  FileKey,
  FileKey2,
  FileLock,
  FileLock2,
  FileMinus,
  FileMinus2,
  FileMusic,
  FileOutput,
  FilePen,
  FilePenLine,
  FilePieChart,
  FilePlus,
  FilePlus2,
  FileQuestion,
  FileScan,
  FileSearch,
  FileSearch2,
  FileSliders,
  FileSpreadsheet,
  FileStack,
  FileSymlink,
  FileTerminal,
  FileText,
  FileType,
  FileType2,
  FileUp,
  FileVideo,
  FileVideo2,
  FileVolume,
  FileVolume2,
  FileWarning,
  FileX,
  FileX2,
  Files,
  Film,
  Filter,
  FilterX,
  Fingerprint,
  FireExtinguisher,
  Fish,
  FishOff,
  Flag,
  FlagOff,
  FlagTriangleLeft,
  FlagTriangleRight,
  Flame,
  FlameKindling,
  Flashlight,
  FlashlightOff,
  FlaskConical,
  FlaskConicalOff,
  FlaskRound,
  FlipHorizontal,
  FlipHorizontal2,
  FlipVertical,
  FlipVertical2,
  Flower,
  Flower2,
  Focus,
  FoldHorizontal,
  FoldVertical,
  Folder,
  FolderArchive,
  FolderCheck,
  FolderClock,
  FolderClosed,
  FolderCode,
  FolderCog,
  FolderDot,
  FolderDown,
  FolderGit,
  FolderGit2,
  FolderHeart,
  FolderInput,
  FolderKanban,
  FolderKey,
  FolderLock,
  FolderMinus,
  FolderOpen,
  FolderOpenDot,
  FolderOutput,
  FolderPen,
  FolderPlus,
  FolderRoot,
  FolderSearch,
  FolderSearch2,
  FolderSymlink,
  FolderSync,
  FolderTree,
  FolderUp,
  FolderX,
  Folders,
  Footprints,
  Forklift,
  FormInput,
  Forward,
  Frame,
  Framer,
  Frown,
  Fuel,
  FunctionSquare,
  Gamepad,
  Gamepad2,
  GanttChart,
  Gauge,
  Gavel,
  Gem,
  Ghost,
  Gift,
  GitBranch,
  GitBranchPlus,
  GitCommit,
  GitCommitHorizontal,
  GitCommitVertical,
  GitCompare,
  GitCompareArrows,
  GitFork,
  GitGraph,
  GitMerge,
  GitPullRequest,
  GitPullRequestArrow,
  GitPullRequestClosed,
  GitPullRequestCreate,
  GitPullRequestCreateArrow,
  GitPullRequestDraft,
  Github,
  Gitlab,
  GlassWater,
  Glasses,
  Globe,
  Globe2,
  Goal,
  Grab,
  GraduationCap,
  Grape,
  Grid,
  Grid2x2,
  Grid2x2Check,
  Grid2x2Plus,
  Grid2x2X,
  Grid3x3,
  Grip,
  GripHorizontal,
  GripVertical,
  Group,
  Guitar,
  Hammer,
  Hand,
  HandCoins,
  HandHeart,
  HandHelping,
  HandMetal,
  HandPlatter,
  Handshake,
  HardDrive,
  HardDriveDownload,
  HardDriveUpload,
  HardHat,
  Hash,
  Haze,
  HdmiPort,
  Heading,
  Heading1,
  Heading2,
  Heading3,
  Heading4,
  Heading5,
  Heading6,
  HeadphoneOff,
  Headphones,
  Headset,
  Heart,
  HeartCrack,
  HeartHandshake,
  HeartOff,
  HeartPulse,
  Heater,
  HelpCircle,
  HelpingHand,
  Hexagon,
  Highlighter,
  History,
  Home,
  HomeIcon,
  Hospital,
  Hotel,
  Hourglass,
  House,
  HousePlug,
  HousePlus,
  IdCard,
  Image,
  ImageDown,
  ImageMinus,
  ImageOff,
  ImagePlus,
  ImageUp,
  Images,
  Import,
  Inbox,
  Indent,
  IndentDecrease,
  IndentIncrease,
  Infinity,
  Info,
  InspectionPanel,
  Instagram,
  IterationCcw,
  IterationCw,
  JapaneseYen,
  Joystick,
  Kanban,
  Key,
  KeyRound,
  KeySquare,
  Keyboard,
  KeyboardMusic,
  Lamp,
  LampCeiling,
  LampDesk,
  LampFloor,
  LampWallDown,
  LampWallUp,
  LandPlot,
  Landmark,
  Languages,
  Laptop,
  LaptopMinimal,
  LaptopMinimalCheck,
  Lasso,
  LassoSelect,
  Laugh,
  Layers,
  LayoutDashboard,
  LayoutGrid,
  LayoutList,
  LayoutPanelLeft,
  LayoutPanelTop,
  LayoutTemplate,
  Leaf,
  LeafyGreen,
  Library,
  LibraryBig,
  LifeBuoy,
  Ligature,
  Lightbulb,
  LightbulbOff,
  LineChart,
  Link,
  Link2,
  Link2Off,
  Linkedin,
  List,
  ListCheck,
  ListChecks,
  ListCollapse,
  ListEnd,
  ListFilter,
  ListMinus,
  ListMusic,
  ListOrdered,
  ListPlus,
  ListRestart,
  ListStart,
  ListTodo,
  ListTree,
  ListVideo,
  ListX,
  Loader,
  Loader2,
  LoaderCircle,
  Locate,
  LocateFixed,
  LocateOff,
  Lock,
  LockKeyhole,
  LockOpen,
  LogIn,
  LogOut,
  Logs,
  Lollipop,
  Luggage,
  Magnet,
  Mail,
  MailCheck,
  MailMinus,
  MailOpen,
  MailPlus,
  MailQuestion,
  MailSearch,
  MailWarning,
  MailX,
  Mailbox,
  Mails,
  Map,
  MapPin,
  MapPinCheck,
  MapPinHouse,
  MapPinMinus,
  MapPinOff,
  MapPinPlus,
  MapPinned,
  MapPlus,
  Mars,
  MarsStroke,
  Martini,
  Maximize,
  Maximize2,
  Medal,
  Megaphone,
  MegaphoneOff,
  Meh,
  MemoryStick,
  Menu,
  MenuSquare,
  Merge,
  MessageCircle,
  MessageCircleCode,
  MessageCircleDashed,
  MessageCircleHeart,
  MessageCircleMore,
  MessageCircleOff,
  MessageCirclePlus,
  MessageCircleQuestion,
  MessageCircleReply,
  MessageCircleWarning,
  MessageCircleX,
  MessageSquare,
  MessageSquareCode,
  MessageSquareDashed,
  MessageSquareDiff,
  MessageSquareDot,
  MessageSquareHeart,
  MessageSquareMore,
  MessageSquareOff,
  MessageSquarePlus,
  MessageSquareQuote,
  MessageSquareReply,
  MessageSquareText,
  MessageSquareWarning,
  MessageSquareX,
  MessagesSquare,
  Mic,
  Mic2,
  MicOff,
  Microscope,
  Microwave,
  Milestone,
  Milk,
  Minimize,
  Minimize2,
  Minus,
  MinusCircle,
  MinusSquare,
  Monitor,
  MonitorCheck,
  MonitorCog,
  MonitorDot,
  MonitorDown,
  MonitorOff,
  MonitorPause,
  MonitorPlay,
  MonitorSmartphone,
  MonitorSpeaker,
  MonitorStop,
  MonitorUp,
  MonitorX,
  Moon,
  MoonStar,
  MoreHorizontal,
  MoreVertical,
  Mountain,
  MountainSnow,
  Mouse,
  MouseOff,
  MousePointer,
  MousePointer2,
  MousePointerBan,
  MousePointerClick,
  Move,
  Move3d,
  MoveDiagonal,
  MoveDiagonal2,
  MoveDown,
  MoveDownLeft,
  MoveDownRight,
  MoveHorizontal,
  MoveLeft,
  MoveRight,
  MoveUp,
  MoveUpLeft,
  MoveUpRight,
  MoveVertical,
  Music,
  Music2,
  Music3,
  Music4,
  Navigation,
  Navigation2,
  Navigation2Off,
  NavigationOff,
  Network,
  Newspaper,
  Nfc,
  Notebook,
  NotebookPen,
  NotebookTabs,
  NotebookText,
  NotepadText,
  NotepadTextDashed,
  Nut,
  NutOff,
  Octagon,
  OctagonAlert,
  OctagonMinus,
  OctagonPause,
  OctagonX,
  Option,
  Orbit,
  Outdent,
  Package,
  Package2,
  PackageCheck,
  PackageMinus,
  PackageOpen,
  PackagePlus,
  PackageSearch,
  PackageX,
  PaintBucket,
  PaintRoller,
  Palette,
  PanelBottom,
  PanelBottomClose,
  PanelBottomDashed,
  PanelBottomOpen,
  PanelLeft,
  PanelLeftClose,
  PanelLeftDashed,
  PanelLeftOpen,
  PanelRight,
  PanelRightClose,
  PanelRightDashed,
  PanelRightOpen,
  PanelTop,
  PanelTopClose,
  PanelTopDashed,
  PanelTopOpen,
  PanelsLeftBottom,
  PanelsRightBottom,
  PanelsTopLeft,
  Paperclip,
  Parentheses,
  ParkingCircle,
  ParkingMeter,
  ParkingSquare,
  PartyPopper,
  Pause,
  PauseCircle,
  PauseOctagon,
  PawPrint,
  PcCase,
  Pen,
  PenBox,
  PenLine,
  PenOff,
  PenTool,
  Pencil,
  PencilLine,
  PencilOff,
  PencilRuler,
  Pentagon,
  Percent,
  PercentCircle,
  PercentDiamond,
  PercentSquare,
  PersonStanding,
  Phone,
  PhoneCall,
  PhoneForwarded,
  PhoneIncoming,
  PhoneMissed,
  PhoneOff,
  PhoneOutgoing,
  Pi,
  Piano,
  Pickaxe,
  PictureInPicture,
  PictureInPicture2,
  PiggyBank,
  Pilcrow,
  PilcrowLeft,
  PilcrowRight,
  Pill,
  PillBottle,
  Pin,
  PinOff,
  Pipette,
  Pizza,
  Plane,
  PlaneLanding,
  PlaneTakeoff,
  Play,
  PlayCircle,
  PlaySquare,
  Plug,
  Plug2,
  PlugZap,
  Plus,
  PlusCircle,
  PlusSquare,
  Pocket,
  PocketKnife,
  Podcast,
  Pointer,
  PointerOff,
  Popcorn,
  Popsicle,
  PoundSterling,
  Power,
  PowerCircle,
  PowerOff,
  PowerSquare,
  Presentation,
  Printer,
  PrinterCheck,
  Projector,
  Proportions,
  Puzzle,
  Pyramid,
  QrCode,
  Quote,
  Rabbit,
  Radar,
  Radiation,
  Radio,
  RadioReceiver,
  RadioTower,
  Radius,
  RailSymbol,
  Rainbow,
  Rat,
  Ratio,
  Receipt,
  ReceiptCent,
  ReceiptEuro,
  ReceiptIndianRupee,
  ReceiptJapaneseYen,
  ReceiptPoundSterling,
  ReceiptRussianRuble,
  ReceiptSwissFranc,
  ReceiptText,
  RectangleEllipsis,
  RectangleHorizontal,
  RectangleVertical,
  Recycle,
  Redo,
  Redo2,
  RedoDot,
  RefreshCcw,
  RefreshCcwDot,
  RefreshCw,
  RefreshCwOff,
  Refrigerator,
  Regex,
  RemoveFormatting,
  Repeat,
  Repeat1,
  Repeat2,
  Replace,
  ReplaceAll,
  Reply,
  ReplyAll,
  Rewind,
  Ribbon,
  Rocket,
  RockingChair,
  RollerCoaster,
  Rotate3d,
  RotateCcw,
  RotateCcwSquare,
  RotateCw,
  RotateCwSquare,
  Route,
  RouteOff,
  Router,
  Rows,
  Rss,
  Ruler,
  RussianRuble,
  Sailboat,
  Salad,
  Sandwich,
  Satellite,
  SatelliteDish,
  Save,
  SaveAll,
  SaveOff,
  Scale,
  Scale3d,
  Scaling,
  Scan,
  ScanBarcode,
  ScanEye,
  ScanFace,
  ScanHeart,
  ScanLine,
  ScanQrCode,
  ScanSearch,
  ScanText,
  ScatterChart,
  School,
  School2,
  Scissors,
  ScissorsLineDashed,
  ScissorsSquare,
  ScissorsSquareDashedBottom,
  ScreenShare,
  ScreenShareOff,
  Scroll,
  ScrollText,
  Search,
  SearchCheck,
  SearchCode,
  SearchSlash,
  SearchX,
  Section,
  Send,
  SendHorizontal,
  SendToBack,
  SeparatorHorizontal,
  SeparatorVertical,
  Server,
  ServerCog,
  ServerCrash,
  ServerOff,
  Settings,
  Settings2,
  Shapes,
  Share,
  Share2,
  Sheet,
  Shell,
  Shield,
  ShieldAlert,
  ShieldBan,
  ShieldCheck,
  ShieldClose,
  ShieldEllipsis,
  ShieldHalf,
  ShieldMinus,
  ShieldOff,
  ShieldPlus,
  ShieldQuestion,
  ShieldX,
  Ship,
  ShipWheel,
  Shirt,
  ShoppingBag,
  ShoppingBasket,
  ShoppingCart,
  Shovel,
  ShowerHead,
  Shrink,
  Shrub,
  Shuffle,
  Sigma,
  Signal,
  SignalHigh,
  SignalLow,
  SignalMedium,
  SignalZero,
  Signature,
  Signpost,
  SignpostBig,
  Siren,
  SkipBack,
  SkipForward,
  Skull,
  Slack,
  Slash,
  Slice,
  Sliders,
  SlidersHorizontal,
  Smartphone,
  SmartphoneCharging,
  SmartphoneNfc,
  Smile,
  SmilePlus,
  Snail,
  Snowflake,
  Sofa,
  SortAsc,
  SortDesc,
  Soup,
  Space,
  Spade,
  Sparkle,
  Sparkles,
  Speaker,
  Speech,
  SpellCheck,
  SpellCheck2,
  Spline,
  Split,
  SplitSquareHorizontal,
  SplitSquareVertical,
  SprayCan,
  Sprout,
  Square,
  SquareActivity,
  SquareArrowDown,
  SquareArrowDownLeft,
  SquareArrowDownRight,
  SquareArrowLeft,
  SquareArrowRight,
  SquareArrowUp,
  SquareArrowUpLeft,
  SquareArrowUpRight,
  SquareAsterisk,
  SquareBottomDashedScissors,
  SquareChartGantt,
  SquareCheck,
  SquareCheckBig,
  SquareCode,
  SquareDashed,
  SquareDashedBottom,
  SquareDashedBottomCode,
  SquareDashedKanban,
  SquareDashedMousePointer,
  SquareDivide,
  SquareDot,
  SquareEqual,
  SquareFunction,
  SquareGanttChart,
  SquareKanban,
  SquareLibrary,
  SquareM,
  SquareMenu,
  SquareMinus,
  SquareMousePointer,
  SquareParking,
  SquareParkingOff,
  SquarePen,
  SquarePercent,
  SquarePi,
  SquarePilcrow,
  SquarePlay,
  SquarePlus,
  SquarePower,
  SquareRadical,
  SquareScissors,
  SquareSigma,
  SquareSlash,
  SquareSplitHorizontal,
  SquareSplitVertical,
  SquareSquare,
  SquareStack,
  SquareTerminal,
  SquareUser,
  SquareUserRound,
  SquareX,
  Squircle,
  Squirrel,
  Stamp,
  Star,
  StarHalf,
  StarOff,
  StepBack,
  StepForward,
  Stethoscope,
  Sticker,
  StickyNote,
  StopCircle,
  Store,
  StretchHorizontal,
  StretchVertical,
  Strikethrough,
  Subscript,
  Sun,
  SunDim,
  SunMedium,
  SunMoon,
  SunSnow,
  Sunrise,
  Sunset,
  Superscript,
  SwatchBook,
  SwissFranc,
  SwitchCamera,
  Sword,
  Swords,
  Syringe,
  Table,
  Table2,
  TableCellsMerge,
  TableCellsSplit,
  TableColumnsSplit,
  TableOfContents,
  TableProperties,
  TableRowsSplit,
  Tablet,
  TabletSmartphone,
  Tablets,
  Tag,
  Tags,
  Tally1,
  Tally2,
  Tally3,
  Tally4,
  Tally5,
  Tangent,
  Target,
  Telescope,
  Tent,
  TentTree,
  Terminal,
  TerminalSquare,
  TestTube,
  TestTube2,
  TestTubes,
  TextCursor,
  TextCursorInput,
  TextQuote,
  TextSearch,
  TextSelect,
  Theater,
  Thermometer,
  ThermometerSnowflake,
  ThermometerSun,
  ThumbsDown,
  ThumbsUp,
  Ticket,
  TicketCheck,
  TicketMinus,
  TicketPercent,
  TicketPlus,
  TicketSlash,
  TicketX,
  Timer,
  TimerOff,
  TimerReset,
  ToggleLeft,
  ToggleRight,
  Tornado,
  Torus,
  Touchpad,
  TouchpadOff,
  TowerControl,
  ToyBrick,
  Tractor,
  TrafficCone,
  Train,
  TrainFront,
  TrainFrontTunnel,
  TrainTrack,
  TramFront,
  Trash,
  Trash2,
  TreeDeciduous,
  TreePine,
  Trees,
  Trello,
  TrendingDown,
  TrendingUp,
  TriangleAlert,
  TriangleRight,
  Trophy,
  Truck,
  Turtle,
  Tv,
  Tv2,
  Twitch,
  Twitter,
  Type,
  TypeOutline,
  Umbrella,
  UmbrellaOff,
  Underline,
  Undo,
  Undo2,
  UndoDot,
  UnfoldHorizontal,
  UnfoldVertical,
  Ungroup,
  University,
  Unlink,
  Unlink2,
  Unlock,
  UnlockKeyhole,
  Unplug,
  Upload,
  Usb,
  User,
  User2,
  UserCheck,
  UserCheck2,
  UserCircle,
  UserCircle2,
  UserCog,
  UserCog2,
  UserMinus,
  UserMinus2,
  UserPen,
  UserPlus,
  UserPlus2,
  UserRound,
  UserRoundCheck,
  UserRoundCog,
  UserRoundMinus,
  UserRoundPen,
  UserRoundPlus,
  UserRoundSearch,
  UserRoundX,
  UserSearch,
  UserX,
  UserX2,
  Users,
  Users2,
  Utensils,
  UtensilsCrossed,
  UtilityPole,
  Variable,
  Vault,
  Vegan,
  VenetianMask,
  Vibrate,
  VibrateOff,
  Video,
  VideoOff,
  Videotape,
  View,
  Voicemail,
  Volume,
  Volume1,
  Volume2,
  VolumeX,
  Vote,
  Wallet,
  Wallet2,
  WalletCards,
  WalletMinimal,
  WalletMinimalIcon,
  Wallpaper,
  Wand,
  Wand2,
  Warehouse,
  WashingMachine,
  Watch,
  Waves,
  Waypoints,
  Webcam,
  Webhook,
  Weight,
  Wheat,
  WheatOff,
  WholeWord,
  Wifi,
  WifiOff,
  Wind,
  Wine,
  WineOff,
  Workflow,
  Worm,
  WrapText,
  Wrench,
  X,
  XCircle,
  XOctagon,
  XSquare,
  Youtube,
  Zap,
  ZapOff,
  ZoomIn,
  ZoomOut,
  PieChart,
} from 'lucide-react';

export const defaultIconSet: IconName = "bolt-filled";

export const iconSets = {
  "bolt-filled": BoltFilled,
  "filled-square": FilledSquare,
  "json": Json,
  "Lovable": Lovable,
  "NodePin": NodePin,
  "NodePlay": NodePlay,
  "NodePower": NodePower,
  "NodeSuccess": NodeSuccess,
  "NodeTrash": NodeTrash,
  "NodeValidationError": NodeValidationError,
  "PopOut": PopOut,
  "Retry": Retry,
  "StatusCanceled": StatusCanceled,
  "StatusCompleted": StatusCompleted,
  "StatusError": StatusError,
  "StatusNew": StatusNew,
  "StatusUnknown": StatusUnknown,
  "StatusWaiting": StatusWaiting,
  "StatusWarning": StatusWarning,
  // "Text": Text,
  "Toolbox": Toolbox,
  "Triangle": Triangle,
  "VectorSquare": VectorSquare,
  // lucide icons
  "align-right": AlignRight,
  "align-left": AlignLeft,
  "align-center": AlignCenter,
  "align-justify": AlignJustify,
  "arrow-left": ArrowLeft,
  "arrow-right": ArrowRight,
  "arrow-up": ArrowUp,
  "arrow-down": ArrowDown,
  "arrow-up-down": ArrowUpDown,
  "arrow-left-right": ArrowLeftRight,
  "activity": Activity,
  "airplay": Airplay,
  "alarm-clock": AlarmClock,
  "alert-circle": AlertCircle,
  "alert-triangle": AlertTriangle,
  "archive": Archive,
  "at-sign": AtSign,
  "award": Award,
  "bar-chart": BarChart,
  "bell": Bell,
  "bell-off": BellOff,
  "bluetooth": Bluetooth,
  "book": Book,
  "bookmark": Bookmark,
  "box": Box,
  "briefcase": Briefcase,
  "calendar": Calendar,
  "camera": Camera,
  "camera-off": CameraOff,
  "check": Check,
  "check-circle": CheckCircle,
  "check-square": CheckSquare,
  "chevron-down": ChevronDown,
  "chevron-left": ChevronLeft,
  "chevron-right": ChevronRight,
  "chevron-up": ChevronUp,
  "chevrons-down": ChevronsDown,
  "chevrons-left": ChevronsLeft,
  "chevrons-right": ChevronsRight,
  "chevrons-up": ChevronsUp,
  "circle": Circle,
  "clipboard": Clipboard,
  "clock": Clock,
  "cloud": Cloud,
  "code": Code,
  "cog": Cog,
  "coins": Coins,
  "command": Command,
  "compass": Compass,
  "copy": Copy,
  "corner-down-left": CornerDownLeft,
  "corner-down-right": CornerDownRight,
  "corner-left-down": CornerLeftDown,
  "corner-left-up": CornerLeftUp,
  "corner-right-down": CornerRightDown,
  "corner-right-up": CornerRightUp,
  "corner-up-left": CornerUpLeft,
  "corner-up-right": CornerUpRight,
  "cpu": Cpu,
  "credit-card": CreditCard,
  "crop": Crop,
  "crosshair": Crosshair,
  "database": Database,
  "delete": Delete,
  "disc": Disc,
  "dollar-sign": DollarSign,
  "download": Download,
  "droplet": Droplet,
  "edit": Edit,
  "edit-2": Edit2,
  "edit-3": Edit3,
  "external-link": ExternalLink,
  "eye": Eye,
  "eye-off": EyeOff,
  "fast-forward": FastForward,
  "file": File,
  "file-text": FileText,
  "film": Film,
  "filter": Filter,
  "flag": Flag,
  "folder": Folder,
  "folder-open": FolderOpen,
  "forward": Forward,
  "frame": Frame,
  "gift": Gift,
  "git-branch": GitBranch,
  "git-commit": GitCommit,
  "git-merge": GitMerge,
  "git-pull-request": GitPullRequest,
  "globe": Globe,
  "grid": Grid,
  "hard-drive": HardDrive,
  "hash": Hash,
  "headphones": Headphones,
  "heart": Heart,
  "help-circle": HelpCircle,
  "hexagon": Hexagon,
  "home": Home,
  "image": Image,
  "inbox": Inbox,
  "info": Info,
  "key": Key,
  "layers": Layers,
  "layout": LayoutDashboard,
  "life-buoy": LifeBuoy,
  "link": Link,
  "link-2": Link2,
  "list": List,
  "loader": Loader,
  "loader-2": Loader2,
  "lock": Lock,
  "log-in": LogIn,
  "log-out": LogOut,
  "mail": Mail,
  "map": Map,
  "map-pin": MapPin,
  "maximize": Maximize,
  "maximize-2": Maximize2,
  "menu": Menu,
  "message-circle": MessageCircle,
  "message-square": MessageSquare,
  "mic": Mic,
  "mic-off": MicOff,
  "minimize": Minimize,
  "minimize-2": Minimize2,
  "minus": Minus,
  "minus-circle": MinusCircle,
  "minus-square": MinusSquare,
  "monitor": Monitor,
  "moon": Moon,
  "more-horizontal": MoreHorizontal,
  "more-vertical": MoreVertical,
  "mouse-pointer": MousePointer,
  "move": Move,
  "music": Music,
  "octagon": Octagon,
  "package": Package,
  "paperclip": Paperclip,
  "pause": Pause,
  "pause-circle": PauseCircle,
  "pen-tool": PenTool,
  "pencil": Pencil,
  "percent": Percent,
  "phone": Phone,
  "phone-call": PhoneCall,
  "phone-forwarded": PhoneForwarded,
  "phone-incoming": PhoneIncoming,
  "phone-missed": PhoneMissed,
  "phone-off": PhoneOff,
  "phone-outgoing": PhoneOutgoing,
  "pie-chart": PieChart,
  "play": Play,
  "play-circle": PlayCircle,
  "plus": Plus,
  "plus-circle": PlusCircle,
  "plus-square": PlusSquare,
  "power": Power,
  "printer": Printer,
  "radio": Radio,
  "refresh-ccw": RefreshCcw,
  "refresh-cw": RefreshCw,
  "repeat": Repeat,
  "rewind": Rewind,
  "rotate-ccw": RotateCcw,
  "rotate-cw": RotateCw,
  "rss": Rss,
  "save": Save,
  "scissors": Scissors,
  "search": Search,
  "send": Send,
  "server": Server,
  "settings": Settings,
  "share": Share,
  "share-2": Share2,
  "shield": Shield,
  "shield-off": ShieldOff,
  "shopping-bag": ShoppingBag,
  "shopping-cart": ShoppingCart,
  "shuffle": Shuffle,
  "sidebar": PanelLeft,
  "skip-back": SkipBack,
  "skip-forward": SkipForward,
  "slash": Slash,
  "sliders": Sliders,
  "smartphone": Smartphone,
  "smile": Smile,
  "speaker": Speaker,
  "square": Square,
  "star": Star,
  "stop-circle": StopCircle,
  "sun": Sun,
  "sunrise": Sunrise,
  "sunset": Sunset,
  "tablet": Tablet,
  "tag": Tag,
  "target": Target,
  "terminal": Terminal,
  "thermometer": Thermometer,
  "thumbs-down": ThumbsDown,
  "thumbs-up": ThumbsUp,
  "toggle-left": ToggleLeft,
  "toggle-right": ToggleRight,
  "trash": Trash,
  "trash-2": Trash2,
  "trending-down": TrendingDown,
  "trending-up": TrendingUp,
  "triangle": Triangle,
  "truck": Truck,
  "tv": Tv,
  "type": Type,
  "umbrella": Umbrella,
  "underline": Underline,
  "undo": Undo,
  "unlink": Unlink,
  "unlock": Unlock,
  "upload": Upload,
  "user": User,
  "user-check": UserCheck,
  "user-minus": UserMinus,
  "user-plus": UserPlus,
  "user-x": UserX,
  "users": Users,
  "video": Video,
  "video-off": VideoOff,
  "voicemail": Voicemail,
  "volume": Volume,
  "volume-1": Volume1,
  "volume-2": Volume2,
  "volume-x": VolumeX,
  "watch": Watch,
  "wifi": Wifi,
  "wifi-off": WifiOff,
  "wind": Wind,
  "x": X,
  "x-circle": XCircle,
  "x-octagon": XOctagon,
  "x-square": XSquare,
  "zap": Zap,
  "zap-off": ZapOff,
  "zoom-in": ZoomIn,
  "zoom-out": ZoomOut,
}

export type IconName = keyof typeof iconSets;

export function isIconName(iconName?: string): iconName is IconName {
  return iconName !== undefined && iconName in iconSets;
}
