import { AppIconSource } from '.';
import { BoltFilled, FilledSquare, Json, Lovable, NodePin, NodePlay, NodePower, NodeSuccess, NodeTrash, NodeValidationError, PopOut, Retry, StatusCanceled, StatusCompleted, StatusError, StatusNew, StatusUnknown, StatusWaiting, StatusWarning, Toolbox, Triangle, VectorSquare } from './custom-generated';
import {
  AlignRight,
  AlignLeft,
  AlignCenter,
  AlignJustify,
  ArrowLeft,
  ArrowRight,
  ArrowUp,
  ArrowDown,
  ArrowUpDown,
  ArrowLeftRight,
  Activity,
  Airplay,
  AlarmClock,
  AlertCircle,
  AlertTriangle,
  Archive,
  AtSign,
  Award,
  BarChart,
  Bell,
  BellOff,
  Bluetooth,
  Book,
  Bookmark,
  Box,
  Briefcase,
  Calendar,
  Camera,
  CameraOff,
  Check,
  CheckCircle,
  CheckSquare,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  ChevronUp,
  ChevronsDown,
  ChevronsLeft,
  ChevronsRight,
  ChevronsUp,
  Circle,
  Clipboard,
  Clock,
  Cloud,
  Code,
  Cog,
  Coins,
  Command,
  Compass,
  Copy,
  CornerDownLeft,
  CornerDownRight,
  CornerLeftDown,
  CornerLeftUp,
  CornerRightDown,
  CornerRightUp,
  CornerUpLeft,
  CornerUpRight,
  Cpu,
  CreditCard,
  Crop,
  Crosshair,
  Database,
  Delete,
  Disc,
  DollarSign,
  Download,
  Droplet,
  Edit,
  Edit2,
  Edit3,
  ExternalLink,
  Eye,
  EyeOff,
  FastForward,
  File,
  FileText,
  Film,
  Filter,
  Flag,
  Folder,
  FolderOpen,
  Forward,
  Frame,
  Gift,
  GitBranch,
  GitCommit,
  GitMerge,
  GitPullRequest,
  Globe,
  Grid,
  HardDrive,
  Hash,
  Headphones,
  Heart,
  HelpCircle,
  Hexagon,
  Home,
  Image,
  Inbox,
  Info,
  Key,
  Layers,
  LayoutDashboard,
  LifeBuoy,
  Link,
  Link2,
  List,
  Loader,
  Loader2,
  Lock,
  LogIn,
  LogOut,
  Mail,
  Map,
  MapPin,
  Maximize,
  Maximize2,
  Menu,
  MessageCircle,
  MessageSquare,
  Mic,
  MicOff,
  Minimize,
  Minimize2,
  Minus,
  MinusCircle,
  MinusSquare,
  Monitor,
  Moon,
  MoreHorizontal,
  MoreVertical,
  MousePointer,
  Move,
  Music,
  Octagon,
  Package,
  PanelLeft,
  Paperclip,
  Pause,
  PauseCircle,
  PenTool,
  Pencil,
  Percent,
  Phone,
  PhoneCall,
  PhoneForwarded,
  PhoneIncoming,
  PhoneMissed,
  PhoneOff,
  PhoneOutgoing,
  Play,
  PlayCircle,
  Plus,
  PlusCircle,
  PlusSquare,
  Power,
  Printer,
  Radio,
  RefreshCcw,
  RefreshCw,
  Repeat,
  Rewind,
  RotateCcw,
  RotateCw,
  Rss,
  Save,
  Scissors,
  Search,
  Send,
  Server,
  Settings,
  Share,
  Share2,
  Shield,
  ShieldOff,
  ShoppingBag,
  ShoppingCart,
  Shuffle,
  SkipBack,
  SkipForward,
  Slash,
  Sliders,
  Smartphone,
  Smile,
  Speaker,
  Square,
  Star,
  StopCircle,
  Sun,
  Sunrise,
  Sunset,
  Tablet,
  Tag,
  Target,
  Terminal,
  Thermometer,
  ThumbsDown,
  ThumbsUp,
  ToggleLeft,
  ToggleRight,
  Trash,
  Trash2,
  TrendingDown,
  TrendingUp,
  Truck,
  Tv,
  Type,
  Umbrella,
  Underline,
  Undo,
  Unlink,
  Unlock,
  Upload,
  User,
  UserCheck,
  UserMinus,
  UserPlus,
  UserX,
  Users,
  Video,
  VideoOff,
  Voicemail,
  Volume,
  Volume1,
  Volume2,
  VolumeX,
  Watch,
  Wifi,
  WifiOff,
  Wind,
  X,
  XCircle,
  XOctagon,
  XSquare,
  Zap,
  ZapOff,
  ZoomIn,
  ZoomOut,
  PieChart,
} from 'lucide-react';

export const defaultIconSet: IconName = "bolt-filled";

export const iconSets = {
  "bolt-filled": BoltFilled,
  "filled-square": FilledSquare,
  "json": Json,
  "Lovable": Lovable,
  "NodePin": NodePin,
  "NodePlay": NodePlay,
  "NodePower": NodePower,
  "NodeSuccess": NodeSuccess,
  "NodeTrash": NodeTrash,
  "NodeValidationError": NodeValidationError,
  "PopOut": PopOut,
  "Retry": Retry,
  "StatusCanceled": StatusCanceled,
  "StatusCompleted": StatusCompleted,
  "StatusError": StatusError,
  "StatusNew": StatusNew,
  "StatusUnknown": StatusUnknown,
  "StatusWaiting": StatusWaiting,
  "StatusWarning": StatusWarning,
  // "Text": Text,
  "Toolbox": Toolbox,
  "Triangle": Triangle,
  "VectorSquare": VectorSquare,
  // lucide icons
  "align-right": AlignRight,
  "align-left": AlignLeft,
  "align-center": AlignCenter,
  "align-justify": AlignJustify,
  "arrow-left": ArrowLeft,
  "arrow-right": ArrowRight,
  "arrow-up": ArrowUp,
  "arrow-down": ArrowDown,
  "arrow-up-down": ArrowUpDown,
  "arrow-left-right": ArrowLeftRight,
  "activity": Activity,
  "airplay": Airplay,
  "alarm-clock": AlarmClock,
  "alert-circle": AlertCircle,
  "alert-triangle": AlertTriangle,
  "archive": Archive,
  "at-sign": AtSign,
  "award": Award,
  "bar-chart": BarChart,
  "bell": Bell,
  "bell-off": BellOff,
  "bluetooth": Bluetooth,
  "book": Book,
  "bookmark": Bookmark,
  "box": Box,
  "briefcase": Briefcase,
  "calendar": Calendar,
  "camera": Camera,
  "camera-off": CameraOff,
  "check": Check,
  "check-circle": CheckCircle,
  "check-square": CheckSquare,
  "chevron-down": ChevronDown,
  "chevron-left": ChevronLeft,
  "chevron-right": ChevronRight,
  "chevron-up": ChevronUp,
  "chevrons-down": ChevronsDown,
  "chevrons-left": ChevronsLeft,
  "chevrons-right": ChevronsRight,
  "chevrons-up": ChevronsUp,
  "circle": Circle,
  "clipboard": Clipboard,
  "clock": Clock,
  "cloud": Cloud,
  "code": Code,
  "cog": Cog,
  "coins": Coins,
  "command": Command,
  "compass": Compass,
  "copy": Copy,
  "corner-down-left": CornerDownLeft,
  "corner-down-right": CornerDownRight,
  "corner-left-down": CornerLeftDown,
  "corner-left-up": CornerLeftUp,
  "corner-right-down": CornerRightDown,
  "corner-right-up": CornerRightUp,
  "corner-up-left": CornerUpLeft,
  "corner-up-right": CornerUpRight,
  "cpu": Cpu,
  "credit-card": CreditCard,
  "crop": Crop,
  "crosshair": Crosshair,
  "database": Database,
  "delete": Delete,
  "disc": Disc,
  "dollar-sign": DollarSign,
  "download": Download,
  "droplet": Droplet,
  "edit": Edit,
  "edit-2": Edit2,
  "edit-3": Edit3,
  "external-link": ExternalLink,
  "eye": Eye,
  "eye-off": EyeOff,
  "fast-forward": FastForward,
  "file": File,
  "file-text": FileText,
  "film": Film,
  "filter": Filter,
  "flag": Flag,
  "folder": Folder,
  "folder-open": FolderOpen,
  "forward": Forward,
  "frame": Frame,
  "gift": Gift,
  "git-branch": GitBranch,
  "git-commit": GitCommit,
  "git-merge": GitMerge,
  "git-pull-request": GitPullRequest,
  "globe": Globe,
  "grid": Grid,
  "hard-drive": HardDrive,
  "hash": Hash,
  "headphones": Headphones,
  "heart": Heart,
  "help-circle": HelpCircle,
  "hexagon": Hexagon,
  "home": Home,
  "image": Image,
  "inbox": Inbox,
  "info": Info,
  "key": Key,
  "layers": Layers,
  "layout": LayoutDashboard,
  "life-buoy": LifeBuoy,
  "link": Link,
  "link-2": Link2,
  "list": List,
  "loader": Loader,
  "loader-2": Loader2,
  "lock": Lock,
  "log-in": LogIn,
  "log-out": LogOut,
  "mail": Mail,
  "map": Map,
  "map-pin": MapPin,
  "maximize": Maximize,
  "maximize-2": Maximize2,
  "menu": Menu,
  "message-circle": MessageCircle,
  "message-square": MessageSquare,
  "mic": Mic,
  "mic-off": MicOff,
  "minimize": Minimize,
  "minimize-2": Minimize2,
  "minus": Minus,
  "minus-circle": MinusCircle,
  "minus-square": MinusSquare,
  "monitor": Monitor,
  "moon": Moon,
  "more-horizontal": MoreHorizontal,
  "more-vertical": MoreVertical,
  "mouse-pointer": MousePointer,
  "move": Move,
  "music": Music,
  "octagon": Octagon,
  "package": Package,
  "paperclip": Paperclip,
  "pause": Pause,
  "pause-circle": PauseCircle,
  "pen-tool": PenTool,
  "pencil": Pencil,
  "percent": Percent,
  "phone": Phone,
  "phone-call": PhoneCall,
  "phone-forwarded": PhoneForwarded,
  "phone-incoming": PhoneIncoming,
  "phone-missed": PhoneMissed,
  "phone-off": PhoneOff,
  "phone-outgoing": PhoneOutgoing,
  "pie-chart": PieChart,
  "play": Play,
  "play-circle": PlayCircle,
  "plus": Plus,
  "plus-circle": PlusCircle,
  "plus-square": PlusSquare,
  "power": Power,
  "printer": Printer,
  "radio": Radio,
  "refresh-ccw": RefreshCcw,
  "refresh-cw": RefreshCw,
  "repeat": Repeat,
  "rewind": Rewind,
  "rotate-ccw": RotateCcw,
  "rotate-cw": RotateCw,
  "rss": Rss,
  "save": Save,
  "scissors": Scissors,
  "search": Search,
  "send": Send,
  "server": Server,
  "settings": Settings,
  "share": Share,
  "share-2": Share2,
  "shield": Shield,
  "shield-off": ShieldOff,
  "shopping-bag": ShoppingBag,
  "shopping-cart": ShoppingCart,
  "shuffle": Shuffle,
  "sidebar": PanelLeft,
  "skip-back": SkipBack,
  "skip-forward": SkipForward,
  "slash": Slash,
  "sliders": Sliders,
  "smartphone": Smartphone,
  "smile": Smile,
  "speaker": Speaker,
  "square": Square,
  "star": Star,
  "stop-circle": StopCircle,
  "sun": Sun,
  "sunrise": Sunrise,
  "sunset": Sunset,
  "tablet": Tablet,
  "tag": Tag,
  "target": Target,
  "terminal": Terminal,
  "thermometer": Thermometer,
  "thumbs-down": ThumbsDown,
  "thumbs-up": ThumbsUp,
  "toggle-left": ToggleLeft,
  "toggle-right": ToggleRight,
  "trash": Trash,
  "trash-2": Trash2,
  "trending-down": TrendingDown,
  "trending-up": TrendingUp,
  "triangle": Triangle,
  "truck": Truck,
  "tv": Tv,
  "type": Type,
  "umbrella": Umbrella,
  "underline": Underline,
  "undo": Undo,
  "unlink": Unlink,
  "unlock": Unlock,
  "upload": Upload,
  "user": User,
  "user-check": UserCheck,
  "user-minus": UserMinus,
  "user-plus": UserPlus,
  "user-x": UserX,
  "users": Users,
  "video": Video,
  "video-off": VideoOff,
  "voicemail": Voicemail,
  "volume": Volume,
  "volume-1": Volume1,
  "volume-2": Volume2,
  "volume-x": VolumeX,
  "watch": Watch,
  "wifi": Wifi,
  "wifi-off": WifiOff,
  "wind": Wind,
  "x": X,
  "x-circle": XCircle,
  "x-octagon": XOctagon,
  "x-square": XSquare,
  "zap": Zap,
  "zap-off": ZapOff,
  "zoom-in": ZoomIn,
  "zoom-out": ZoomOut,
}

export type IconName = keyof typeof iconSets;

export function isIconName(iconName?: string): iconName is IconName {
  return iconName !== undefined && iconName in iconSets;
}

export const getDefaultIcon = (iconType: AppIconSource['type'], customIcon?: string): string => {
  if (iconType === 'emoji') {
    // emoji 类型：返回自定义 emoji 或默认 emoji
    return customIcon || '🐤'; // 默认 emoji
  } else {
    // icon 类型：返回自定义图标集或默认图标集
    return customIcon || defaultIconSet;
  }
};