export const DefaultConfigValues = {
    CODE_EXECUTION_CONNECT_TIMEOUT: 10.0,
    CODE_EXECUTION_READ_TIMEOUT: 60.0,
    CODE_EXECUTION_WRITE_TIMEOUT: 60.0,
    CODE_EXECUTION_MAX_NUMBER: 9000000000000,
    CODE_EXECUTION_MIN_NUMBER: -9000000000000,
    CODE_MAX_DEPTH: 5,
    CODE_MAX_PRECISION: 20,
    CODE_MAX_STRING_LENGTH: 30,
    CODE_MAX_OBJECT_ARRAY_LENGTH: 30,
    CODE_MAX_NUMBER_ARRAY_LENGTH: 1000,


    APP_MAX_EXECUTION_TIME: 1200,
    APP_MAX_ACTIVE_REQUESTS: 0,
    APP_MAX_RATE_LIMIT: 5000,

    PLUGIN_MAX_PACKAGE_SIZE: 15728640,

    REDIS_HOST: 'localhost',
    REDIS_PORT: 6379,
    REDIS_USE_SSL: false,
    REDIS_USE_CLUSTER: false,
    REDIS_SERIALIZATION_PROTOCOL: 3,
    REDIS_ENABLE_CLIENT_SIDE_CACHE: false,

    RESET_PASSWORD_TOKEN_EXPIRY_MINUTES: 5,
    EMAIL_CODE_LOGIN_EXPIRY_MINUTES: 5,
    CHANGE_EMAIL_TOKEN_EXPIRY_MINUTES: 5,
    ACCOUNT_DELETION_TOKEN_EXPIRY_MINUTES: 60,

    // Maximum file size for uploads in MB
    UPLOAD_FILE_SIZE_LIMIT: 15,
    // Maximum number of files in a batch upload
    UPLOAD_FILE_BATCH_LIMIT: 5,
    // Maximum image file size in MB
    UPLOAD_IMAGE_FILE_SIZE_LIMIT: 10,
    // Maximum video file size in MB
    UPLOAD_VIDEO_FILE_SIZE_LIMIT: 100,
    // Maximum audio file size in MB
    UPLOAD_AUDIO_FILE_SIZE_LIMIT: 50,
    // Maximum number of files in a batch upload
    BATCH_UPLOAD_LIMIT: 20,
    // Maximum number of files for workflow file upload
    WORKFLOW_FILE_UPLOAD_LIMIT: 10,

    HTTP_REQUEST_MAX_CONNECT_TIMEOUT: 10,
    HTTP_REQUEST_MAX_READ_TIMEOUT: 60,
    HTTP_REQUEST_MAX_WRITE_TIMEOUT: 20,
    HTTP_REQUEST_NODE_MAX_BINARY_SIZE: 10 * 1024 * 1024,
    HTTP_REQUEST_NODE_MAX_TEXT_SIZE: 1 * 1024 * 1024,
    SSRF_DEFAULT_MAX_RETRIES: 3,
    HTTP_REQUEST_SSL_VERIFICATION_ENABLED: true,
    HTTP_REQUEST_MAX_BINARY_SIZE: 10 * 1024 * 1024,
    HTTP_REQUEST_MAX_TEXT_SIZE: 1 * 1024 * 1024,

    ACCESS_TOKEN_EXPIRY_MINUTES: 60,
    REFRESH_TOKEN_EXPIRY_DAYS: 30,
    LOGIN_RETRY_DURATION_MINUTES: 86400,
    FORGOT_PASSWORD_RETRY_DURATION_MINUTES: 86400,

    CACHE_TTL: 5000,
    CACHE_LRU_SIZE: 5000,
};
