export type DataTableConfig = typeof dataTableConfig;

export const dataTableConfig = {
    textOperators: [
        { label: 'Contains', value: 'iLike' as const },
        { label: 'Does not contain', value: 'notILike' as const },
        { label: 'Is', value: 'eq' as const },
        { label: 'Is not', value: 'notEq' as const },
        { label: 'Is empty', value: 'isEmtpy' as const },
        { label: 'Is not empty', value: 'isNotEmpty' as const },
    ],
    numericOperators: [
        { label: 'Is', value: 'eq' as const },
        { label: 'Is not', value: 'ne' as const },
        { label: 'Is greater than', value: 'gt' as const },
        { label: 'Is less than', value: 'lt' as const },
        { label: 'Is greater than or equal to', value: 'gte' as const },
        { label: 'Is less than or equal to', value: 'lte' as const },
        { label: 'Is empty', value: 'isEmtpy' as const },
        { label: 'Is not empty', value: 'isNotEmpty' as const },
        { label: 'Is between', value: 'isBetween' as const },
    ],
    selectOperators: [
        { label: 'Is', value: 'eq' as const },
        { label: 'Is not', value: 'ne' as const },
        { label: 'Is empty', value: 'isEmtpy' as const },
        { label: 'Is not empty', value: 'isNotEmpty' as const },
    ],
    multiSelectOperators: [
        { label: 'Contains', value: 'has' as const },
        { label: 'Does not contain', value: 'notHas' as const },
        { label: 'Is empty', value: 'isEmtpy' as const },
        { label: 'Is not empty', value: 'isNotEmpty' as const },
    ],
    dateOperators: [
        { label: 'Is', value: 'eq' as const },
        { label: 'Is not', value: 'ne' as const },
        { label: 'Is before', value: 'lt' as const },
        { label: 'Is after', value: 'gt' as const },
        { label: 'Is on or before', value: 'lte' as const },   
    ],
    booleanOperators: [
        { label: 'Is true', value: 'eq' as const },
        { label: 'Is false', value: 'ne' as const },
        { label: 'Is empty', value: 'isEmtpy' as const },
        { label: 'Is not empty', value: 'isNotEmpty' as const },
    ],
    sortOperators: [
        { label: 'Ascending', value: 'asc' as const },
        { label: 'Descending', value: 'desc' as const },
    ],
    filterVariants: [
        'text',
        'number',
        'boolean',
        'range',
        'date',
        'dateRange',
        'select',
        'multiSelect',
    ] as const,
    operators: [
        'iLike',
        'notILike',
        'eq',
        'notEq',
        'isEmtpy',
        'isNotEmpty',
        'ne',
        'gt',
        'lt',
        'gte',
        'lte',
        'isBetween',
        'has',
        'notHas',
        'is',
        'isNot',
        'isEmpty',
        'isBefore',
    ] as const,
    joinOperators: [
        'and',
        'or',
    ] as const,
};
